version: '2'

services:
  swarmproxy:    
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf      
    ports:
      - "8080:80"

networks:
  default:    
    driver: overlay
    
