version: '2'

services:
  swarmproxy:    
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    networks:
      - dmz        
    ports:
      - "8080:80"

networks:
  dmz:
    external: true
      name: dmz
    